-- MySQL Script generated by MySQL Workbench
-- Κυρ 27 Ιαν 2019 01:47:56 πμ EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AndroidDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AndroidDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AndroidDB` DEFAULT CHARACTER SET utf8 ;
USE `AndroidDB` ;

-- -----------------------------------------------------
-- Table `AndroidDB`.`Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AndroidDB`.`Details` (
  `PhoneName` VARCHAR(100) NULL,
  `TimeStamp` VARCHAR(100) NULL,
  `GPSCoord` VARCHAR(100) NULL,
  `CriticalityLevel` INT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
